property page with navigation.
revdev-earth/properties pull request #1
Opened 2024-10-29 14:15 UTC by nickothan

2024-10-29 16:27 UTC, revione commented
All inside the project should have to be in english

2024-10-29 16:32 UTC, revione commented
Follow this pattern
LAS-8: adding navigation

2024-10-30 12:39 UTC, revione requested changes

2024-10-30 12:39 UTC, revione commented on src/app/dashboard/property/navLinks.tsx
> +    <nav className="flex gap-5">
It should have to be an array

2024-10-30 12:39 UTC, revione commented on src/app/dashboard/property/page.tsx
> +  return <div>property</div>;
I dont see the image and the other information

2024-10-30 12:39 UTC, revione commented on src/app/dashboard/property/template.tsx
> +        src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSEhUTEhIVFhUVFRcVFRYXFRUVFxUWFRUWFhcVFRcYHSggGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQGy0lHyUtLS8vLS0tLS0tLS0tLS0tLS0
why is this commented?

2024-10-30 12:39 UTC, revione commented on src/app/dashboard/property/tenats/page.tsx
> +      <h2>tenats</h2>
first letter uppercase!

2024-10-31 18:30 UTC, revione requested changes

2024-10-31 18:30 UTC, revione commented on src/app/dashboard/property/navLinks.tsx
> +    <nav className="flex gap-5">
??

2024-10-31 18:30 UTC, revione commented on src/app/dashboard/property/page.tsx
> +  return <div>property</div>;
??

2024-10-31 18:30 UTC, revione commented on src/app/dashboard/property/template.tsx
> +        src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSEhUTEhIVFhUVFRcVFRYXFRUVFxUWFRUWFhcVFRcYHSggGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQGy0lHyUtLS8vLS0tLS0tLS0tLS0tLS0
??

2024-10-31 18:30 UTC, revione commented on src/app/dashboard/property/tenats/page.tsx
> +      <h2>tenats</h2>
??

2024-11-01 00:03 UTC, nickothan commented on src/app/dashboard/property/navLinks.tsx
> +    <nav className="flex gap-5">
ok

2024-11-01 00:32 UTC, nickothan commented on src/app/dashboard/property/template.tsx
> +        src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSEhUTEhIVFhUVFRcVFRYXFRUVFxUWFRUWFhcVFRcYHSggGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQGy0lHyUtLS8vLS0tLS0tLS0tLS0tLS0
ok

2024-11-01 14:44 UTC, revione commented on src/app/dashboard/property/page.tsx
> +  return <div>property</div>;
do you have any question related to this?

2024-11-01 14:44 UTC, revione commented on src/app/dashboard/property/tenats/page.tsx
> +      <h2>tenats</h2>
do you have any question related to this?

2024-11-01 15:31 UTC, merged